### ISSUE TITLE
Command handling

### ISSUE THREAD

**Issue by ghost** [tabrath/ChatApp#11]
@tabrath Found you on Youtube, Epic tutorial but I can see you can handle your current and future commands better using this https://github.com/theouteredge/cmdR

**Comment by tabrath** [comment]
Yeah, I'm aware there are plenty of command line parsers out there. But the long term goal of this project is not a command-line app, rather a desktop app using WPF. But hey, thanks for watching! I'm hoping I'll have time to get back to the project in a few days.

**Comment by ghost** [comment]
👍
